server:
  port: 9000
  servlet:
    context-path: /idata

spring:
  profiles:
    active: dev
  ##把数据库日期格式转换成json返回页面的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false


#spring-boot整合mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

constant:
  antMatchers: /,/login,/page/portal/**,/favicon.ico,/images/**,/AdminLTE-3.0.2/**,/js/**,/css/**,/plugins/**,/webjars/**


logging:
  level:
    com.wonders: debug
    # 启动时打印请求路径列表
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
