server:
  port: 9000
  servlet:
    context-path: /idata

spring:
  profiles:
    active: dev
  ##把数据库日期格式转换成json返回页面的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  security:
    # springsecurity不拦截的路径，以,分割
    antMatchers:
      - /favicon.ico,/images/**,/AdminLTE-3.0.2/**,/js/**,/css/**,/plugins/**,/webjars/**
      - /,/login,/page/portal/**
      - /swagger-ui.html,/swagger-resources/**,/v2/**
    # 用户免登陆时间，单位s--1周
    rememberMeSeconds: 604800
    # 短信登录地址
    smsLoginUrl: /login/smsLogin



#spring-boot整合mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true



logging:
  level:
    com.wonders: debug
    # 启动时打印请求路径列表
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
swagger:
  enabled: true
  title: iData接口文档
  description: 测试环境下启动的swagger2接口测试
  base-package: com.wonders.controller
  base-path: /**

