server:
  port: 9000
  servlet:
    context-path: /idata
    session:
      timeout: 30m
  # 开启gzip压缩，默认情况下，仅会压缩 2048 字节以上的内容
  compression:
    enabled: true
    min-response-size: 2KB

spring:
  profiles:
    active: prod
  #把数据库日期格式转换成json返回页面的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always

  thymeleaf:
    cache: false

#spring-boot整合mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.wonders: debug
    # 启动时打印请求路径列表
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
swagger:
  enabled: false
  title: iData接口文档
  description: 测试环境下启动的swagger2接口测试
  base-package: com.wonders.controller
  base-path: /**

idata:
  security:
    # springsecurity不拦截的路径，以,分割
    antMatchers:
      - /favicon.ico,/images/**,/AdminLTE-3.0.2/**,/js/**,/css/**,/plugins/**,/webjars/**
      - /,/login,/introduction/**,/package/**
      - /swagger-ui.html,/swagger-resources/**,/v2/**
    # 用户免登陆时间，单位s（604800：1周）
    rememberMeSeconds: 604800
    rememberMeCookieName: rm
    # 短信登录地址
    smsLoginUrl: /login/smsLogin
  file:
    avatarPath: /avatar
    avatarLocation: file/avatar
    defaultAvatar: /images/u3255.png


