server:
  port: 9000
  servlet:
    context-path: /idata

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.133.222.228:3306/idata?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1qaz@WSX

swagger:
  enabled: false

logging:
  config: classpath:logback-spring-prod.xml
